name: tnews
description: A new project template with Flutter.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: 0.5.1
  cupertino_icons: 0.1.2
  flutter_bloc: ^2.0.0
  shared_preferences: ^0.5.3+4

  tnews_core:
    path: tnews_core

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.2+1
  json_serializable: ^2.0.0
  pedantic: ^1.8.0+1
  flutter_native_splash: ^0.1.9
    


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icons/logo.png"
  build_runner: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audios/
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/videos/

  fonts:
    - family: Sarabun
      fonts:
        - asset: assets/fonts/sarabun/Sarabun-Thin.ttf
          weight: 100
        - asset: assets/fonts/sarabun/Sarabun-ThinItalic.ttf
          weight: 100
          style: italic

        - asset: assets/fonts/sarabun/Sarabun-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/sarabun/Sarabun-ExtraLightItalic.ttf
          weight: 200
          style: italic

        - asset: assets/fonts/sarabun/Sarabun-Light.ttf
          weight: 300
        - asset: assets/fonts/sarabun/Sarabun-LightItalic.ttf
          weight: 300
          style: italic

        - asset: assets/fonts/sarabun/Sarabun-Regular.ttf
          weight: 400
        - asset: assets/fonts/sarabun/Sarabun-Italic.ttf
          style: italic

        - asset: assets/fonts/sarabun/Sarabun-Medium.ttf
          weight: 500
        - asset: assets/fonts/sarabun/Sarabun-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/sarabun/Sarabun-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/sarabun/Sarabun-SemiBoldItalic.ttf
          weight: 600
          style: italic

        - asset: assets/fonts/sarabun/Sarabun-Bold.ttf
          weight: 700
        - asset: assets/fonts/sarabun/Sarabun-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/sarabun/Sarabun-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/sarabun/Sarabun-ExtraBoldItalic.ttf
          weight: 800
          style: italic
