name: tnews_core
description: t_core module

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  intl: 0.16.1
  equatable: 1.1.1
  shared_preferences: 0.5.7+3
  dio: 3.0.9
  path_provider: 1.6.9
  flutter_cache_manager: 1.2.2
  ansicolor: 1.0.2
  
  ddi:
    path: ../packages/di

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 4.1.1
  test: ^1.0.0
  json_serializable: 3.3.0
  json_annotation: 3.0.1
