name: tnews_core
description: t_core module

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  intl: 0.16.1
  equatable: 1.1.1
  shared_preferences: 0.5.7+3
  dio: ^5.0.3
  path_provider: ^2.0.14
  flutter_cache_manager: ^3.3.0
  ansicolor: 1.0.2
  
  ddi:
    path: ../packages/di

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  test: ^1.22.0
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0
